services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
      - "5342:5342"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  fileupload.api:
    build:
      context: .
      dockerfile: FileUpload.API/Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Serilog__WriteTo__0__Name=Seq
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    depends_on:
      - rabbitmq
      - seq
    volumes:
      - uploads:/app/uploads:rw

  fileupload.worker:
    build:
      context: .
      dockerfile: FileUpload.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__0__Name=Seq
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    depends_on:
      - rabbitmq
      - fileupload.api
      - seq
    volumes:
      - uploads:/app/uploads:rw

  fileupload.notification:
    build:
      context: .
      dockerfile: FileUpload.Notification/Dockerfile
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Serilog__WriteTo__0__Name=Seq
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    depends_on:
      - rabbitmq
      - seq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  order.notifications:
    image: ${DOCKER_REGISTRY-}ordernotifications
    build:
      context: .
      dockerfile: Order.Notifications/Dockerfile
    ports  :
      - "7002:8080"
      - "7003:8081"

volumes:
  rabbitmq_data:
  uploads:
  seq_data: 
  redis_data:
